### ISSUE TITLE
Add Whitelist for Infoblox Zone Cache feature

### ISSUE THREAD

**Issue by christianhuening** [gardener/external-dns-management#332]
**What would you like to be added**:
When the infoblox provider creates its initial zone cache, by default it downloads the complete zone list and then gets all records for all zones except for an optional blacklist. We would like to have that narrowed down by a whitelist additionally.

**Why is this needed**:
In our case we map a set of sub-zones to a specific k8s cluster and hence know exactly for which zones workload on that cluster may request entries. To optimize performance we need this enhancement.

**Comment by MartinWeindel** [comment]
Instead of implementing a whitelist, it is planned to change the behaviour of the dns-controller-manager.
It should avoid to read records from unused zones periodically only to find "foreign" domains (`NS` records for subdomains).
See #336 (Drop retrieval of foreign domains to avoid synching unused hosted zones)

**Comment by christianhuening** [comment]
closing this issue, since #336 has been merged and is working quite well. thanks :)
