### ISSUE TITLE
ControllerRegistration tag is out of sync

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/external-dns-management#84]
**What would you like to be added**:
You can notice that for all of the extension controllers in the gardener org when you go to the example ControllerRegistration for given tag in git, the image tag in the ControllerRegistration will be the same as the git tag. For example see https://github.com/gardener/gardener-extension-provider-aws/blob/v1.7.1/example/controller-registration.yaml.

At least for me, this is convenient when applying ControllerRegistration. It is simply:
```
$ k apply -f https://github.com/gardener/gardener-extension-provider-aws/blob/v1.7.1/example/controller-registration.yaml
```

I tried the same for external-dns-management:
```
$ k apply -f https://raw.githubusercontent.com/gardener/external-dns-management/v0.7.11/examples/controller-registration.yaml
```

But you can notice that for https://raw.githubusercontent.com/gardener/external-dns-management/v0.7.11/examples/controller-registration.yaml, the image tag is `v0.7.7-dev` (the one I expect is to be `v0.7.11`, same as the git tag).

**Why is this needed**:
To make it easy when applying your ControllerRegistrations in your (local) setup.

**Comment by MartinWeindel** [comment]
The problem was introduced with #54. In this PR, the controller-registration.yaml has been renamed to gardener-controllerregistration.yaml.
So you can find the correct controller-registration as https://raw.githubusercontent.com/gardener/external-dns-management/v0.7.11/examples/gardener-controllerregistration.yaml

But I will provide a PR for that

**Comment by ialidzhikov** [comment]
Thank you @MartinWeindel !
